### ISSUE TITLE
百度数据集结果

### ISSUE THREAD

**Issue by yxk9810** [wuyaoxuehun/colbert#1]
hi，
想知道你有在百度公开数据集上跑的结果么？我使用colbert v1官方代码在百度数据集上，效果比bm25差了很多

**Comment by wuyaoxuehun** [comment]
你说的是百度段落检索竞赛的那个数据集么，你可以参考https://aistudio.baidu.com/aistudio/competition/detail/157/0/leaderboard
段落检索 离线评测里面第9名是本repo的结果。
复现有问题可以再具体提出来。
祝好。
